# Alternative IMAP configurations for mx.qraex.de
# Copy one of these configurations into config/imap.yml if the default configuration does not work

# Option 1: Port 143 without SSL
default: &default
  host: mx.qraex.de
  port: 143
  ssl: false
  username: <%= ENV['IMAP_USERNAME'] %>
  password: <%= ENV['IMAP_PASSWORD'] %>
  folder: INBOX
  subject_filter: "The Briefing"
  max_emails: 10

# Option 2: Port 993 with SSL/TLS
# default: &default
#   host: mx.qraex.de
#   port: 993
#   ssl: true
#   username: <%= ENV['IMAP_USERNAME'] %>
#   password: <%= ENV['IMAP_PASSWORD'] %>
#   folder: INBOX
#   subject_filter: "The Briefing"
#   max_emails: 10

# Option 3: Port 587 (SMTP port, if IMAP is not available)
# default: &default
#   host: mx.qraex.de
#   port: 587
#   ssl: false
#   username: <%= ENV['IMAP_USERNAME'] %>
#   password: <%= ENV['IMAP_PASSWORD'] %>
#   folder: INBOX
#   subject_filter: "The Briefing"
#   max_emails: 10

development:
  <<: *default

production:
  <<: *default
